### PR TITLE
Feature C

### PR DESCRIPTION
**Pull request by vibrantfervor**
Completed feature C

### CODE REVIEW

**Comment by Mkrichmar** [comment]
lgtm!

**Comment by Mkrichmar** [comment]
Hey David, what’s your last name? I wanted to connect on slack so we could
schedule some time to work on the next stage together. Will you be
available today at all before class?

**Comment by vibrantfervor** [comment]
>My last name is Beaudet

**Comment by Mkrichmar** [comment]
I just sent a slack invite, did you get it?

**Pull request merged**
